{"name": "登录接口--错误的用户名、密码", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert '99998' == '0'\n  - 0\n  + 99998", "trace": "@pytest.mark.xfail\n    @allure.feature(\"媒资库后台管理\")\n    @allure.story(\"管理后台User接口\")\n    @allure.title(\"登录接口--错误的用户名、密码\")\n    @allure.description(\"传入错误的用户名、密码\")\n    def test_login002():\n        username=data['login'][1]['Params']['username']\n        password=data['login'][1]['Params']['password']\n        # 对密码进行加密\n        password = get_str_sha1(password)\n        response=login(username=username,password=password)\n        # 断言\n>       assert response['response']['code'] == '0'\nE       AssertionError: assert '99998' == '0'\nE         - 0\nE         + 99998\n\nlogin\\test_login.py:37: AssertionError"}, "description": "传入错误的用户名、密码", "attachments": [{"name": "log", "source": "45092209-ba62-49a6-b471-238ceb6b86e0-attachment.txt", "type": "text/plain"}], "start": 1629165740539, "stop": 1629165740568, "uuid": "e378b8d3-2ffd-42b3-84ed-39ff9bde6d54", "historyId": "6c2d5e23d177d55b3d9b9a41b743bb8a", "testCaseId": "fe2aadb86bc1b06b02c16fdffe4bf7bb", "fullName": "login.test_login#test_login002", "labels": [{"name": "feature", "value": "媒资库后台管理"}, {"name": "story", "value": "管理后台User接口"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "login"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-03G54LT"}, {"name": "thread", "value": "11328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login.test_login"}]}