{"name": "登录接口--错误的用户名、正确的密码", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert '99998' == '0'\n  - 0\n  + 99998", "trace": "@pytest.mark.xfail\n    @allure.feature(\"媒资库后台管理\")\n    @allure.story(\"管理后台User接口\")\n    @allure.title(\"登录接口--错误的用户名、正确的密码\")\n    @allure.description(\"传入错误的用户名、正确的密码\")\n    def test_login004():\n        username=data['login'][3]['Params']['username']\n        password=data['login'][3]['Params']['password']\n        # 对密码进行加密\n        password = get_str_sha1(password)\n        response=login(username=username,password=password)\n        # 断言\n>       assert response['response']['code'] == '0'\nE       AssertionError: assert '99998' == '0'\nE         - 0\nE         + 99998\n\nlogin\\test_login.py:65: AssertionError"}, "description": "传入错误的用户名、正确的密码", "attachments": [{"name": "log", "source": "d96e4b78-5aa2-4288-a04c-64223b6f225c-attachment.txt", "type": "text/plain"}], "start": 1629095824084, "stop": 1629095824167, "uuid": "a952a01f-00d5-4b37-a1f0-2a7a1e3a053e", "historyId": "c8691c671ade3e24f6633c2f2f9eca33", "testCaseId": "662a138e77a79d9e380467f658e4ea44", "fullName": "login.test_login#test_login004", "labels": [{"name": "feature", "value": "媒资库后台管理"}, {"name": "story", "value": "管理后台User接口"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "login"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-03G54LT"}, {"name": "thread", "value": "11284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login.test_login"}]}